//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsoleClient.NotificationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NotificationService.INotificationContract", CallbackContract=typeof(TestConsoleClient.NotificationService.INotificationContractCallback))]
    public interface INotificationContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationContract/Subscribe", ReplyAction="http://tempuri.org/INotificationContract/SubscribeResponse")]
        bool Subscribe(DataTransferObjects.AuthenticationToken token, int boardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationContract/Subscribe", ReplyAction="http://tempuri.org/INotificationContract/SubscribeResponse")]
        System.Threading.Tasks.Task<bool> SubscribeAsync(DataTransferObjects.AuthenticationToken token, int boardId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotificationContractCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationContract/OnBoardAdded", ReplyAction="http://tempuri.org/INotificationContract/OnBoardAddedResponse")]
        void OnBoardAdded(DataTransferObjects.BoardDTO board);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationContract/OnParticipantAdded", ReplyAction="http://tempuri.org/INotificationContract/OnParticipantAddedResponse")]
        void OnParticipantAdded(DataTransferObjects.UserDTO user, int boardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationContract/OnColumnAdded", ReplyAction="http://tempuri.org/INotificationContract/OnColumnAddedResponse")]
        void OnColumnAdded(DataTransferObjects.ColumnDTO column, int boardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationContract/OnBoardTagAdded", ReplyAction="http://tempuri.org/INotificationContract/OnBoardTagAddedResponse")]
        void OnBoardTagAdded(DataTransferObjects.TagDTO tag, int boardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationContract/OnCardTagAdded", ReplyAction="http://tempuri.org/INotificationContract/OnCardTagAddedResponse")]
        void OnCardTagAdded(int tagId, int cardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationContract/OnHistoryEventAdded", ReplyAction="http://tempuri.org/INotificationContract/OnHistoryEventAddedResponse")]
        void OnHistoryEventAdded(DataTransferObjects.HistoryEventDTO historyEvent, int boardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationContract/OnCardAdded", ReplyAction="http://tempuri.org/INotificationContract/OnCardAddedResponse")]
        void OnCardAdded(DataTransferObjects.CardDTO card, int columnId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationContract/OnCardSubscribersAdded", ReplyAction="http://tempuri.org/INotificationContract/OnCardSubscribersAddedResponse")]
        void OnCardSubscribersAdded(DataTransferObjects.UserDTO user, int cardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationContract/OnCardCommentAdded", ReplyAction="http://tempuri.org/INotificationContract/OnCardCommentAddedResponse")]
        void OnCardCommentAdded(DataTransferObjects.CommentDTO comment, int cardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationContract/OnBoardDeleted", ReplyAction="http://tempuri.org/INotificationContract/OnBoardDeletedResponse")]
        void OnBoardDeleted(int boardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationContract/OnColumnDeleted", ReplyAction="http://tempuri.org/INotificationContract/OnColumnDeletedResponse")]
        void OnColumnDeleted(int boardId, int columnId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationContract/OnBoardTagDeleted", ReplyAction="http://tempuri.org/INotificationContract/OnBoardTagDeletedResponse")]
        void OnBoardTagDeleted(int boardId, int tagId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationContract/OnCardDeleted", ReplyAction="http://tempuri.org/INotificationContract/OnCardDeletedResponse")]
        void OnCardDeleted(int boardId, int columnId, int cardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationContract/OnCardTagDeleted", ReplyAction="http://tempuri.org/INotificationContract/OnCardTagDeletedResponse")]
        void OnCardTagDeleted(int boardId, int cardId, int tagId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotificationContractChannel : TestConsoleClient.NotificationService.INotificationContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificationContractClient : System.ServiceModel.DuplexClientBase<TestConsoleClient.NotificationService.INotificationContract>, TestConsoleClient.NotificationService.INotificationContract {
        
        public NotificationContractClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public NotificationContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public NotificationContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationContractClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool Subscribe(DataTransferObjects.AuthenticationToken token, int boardId) {
            return base.Channel.Subscribe(token, boardId);
        }
        
        public System.Threading.Tasks.Task<bool> SubscribeAsync(DataTransferObjects.AuthenticationToken token, int boardId) {
            return base.Channel.SubscribeAsync(token, boardId);
        }
    }
}
