//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.NotificationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NotificationService.INotificationContract", CallbackContract=typeof(PresentationLayer.NotificationService.INotificationContractCallback))]
    public interface INotificationContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationContract/Subscribe", ReplyAction="http://tempuri.org/INotificationContract/SubscribeResponse")]
        bool Subscribe(DataTransferObjects.AuthenticationToken token, int boardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationContract/Subscribe", ReplyAction="http://tempuri.org/INotificationContract/SubscribeResponse")]
        System.Threading.Tasks.Task<bool> SubscribeAsync(DataTransferObjects.AuthenticationToken token, int boardId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotificationContractCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INotificationContract/OnBoardAdded")]
        void OnBoardAdded(DataTransferObjects.BoardDTO board);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INotificationContract/OnParticipantAdded")]
        void OnParticipantAdded(DataTransferObjects.UserDTO user, int boardId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INotificationContract/OnColumnAdded")]
        void OnColumnAdded(DataTransferObjects.ColumnDTO column, int boardId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INotificationContract/OnBoardTagAdded")]
        void OnBoardTagAdded(DataTransferObjects.TagDTO tag, int boardId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INotificationContract/OnCardTagAdded")]
        void OnCardTagAdded(int tagId, int cardId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INotificationContract/OnHistoryEventAdded")]
        void OnHistoryEventAdded(DataTransferObjects.HistoryEventDTO historyEvent, int boardId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INotificationContract/OnCardAdded")]
        void OnCardAdded(DataTransferObjects.CardDTO card, int columnId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INotificationContract/OnCardSubscribersAdded")]
        void OnCardSubscribersAdded(DataTransferObjects.UserDTO user, int cardId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INotificationContract/OnCardCommentAdded")]
        void OnCardCommentAdded(DataTransferObjects.CommentDTO comment, int cardId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INotificationContract/OnBoardDeleted")]
        void OnBoardDeleted(int boardId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INotificationContract/OnColumnDeleted")]
        void OnColumnDeleted(int boardId, int columnId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INotificationContract/OnBoardTagDeleted")]
        void OnBoardTagDeleted(int boardId, int tagId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INotificationContract/OnCardDeleted")]
        void OnCardDeleted(int boardId, int columnId, int cardId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INotificationContract/OnCardTagDeleted")]
        void OnCardTagDeleted(int boardId, int cardId, int tagId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INotificationContract/OnCardMoved")]
        void OnCardMoved(int cardId, int originalColumnId, int destinationColumnId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotificationContractChannel : PresentationLayer.NotificationService.INotificationContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificationContractClient : System.ServiceModel.DuplexClientBase<PresentationLayer.NotificationService.INotificationContract>, PresentationLayer.NotificationService.INotificationContract {
        
        public NotificationContractClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public NotificationContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public NotificationContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationContractClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool Subscribe(DataTransferObjects.AuthenticationToken token, int boardId) {
            return base.Channel.Subscribe(token, boardId);
        }
        
        public System.Threading.Tasks.Task<bool> SubscribeAsync(DataTransferObjects.AuthenticationToken token, int boardId) {
            return base.Channel.SubscribeAsync(token, boardId);
        }
    }
}
