//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsoleClient.EditionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EditionService.IEditionContract")]
    public interface IEditionContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEditionContract/EditCard", ReplyAction="http://tempuri.org/IEditionContract/EditCardResponse")]
        bool EditCard(DataTransferObjects.AuthenticationToken token, DataTransferObjects.CardDTO card);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEditionContract/EditCard", ReplyAction="http://tempuri.org/IEditionContract/EditCardResponse")]
        System.Threading.Tasks.Task<bool> EditCardAsync(DataTransferObjects.AuthenticationToken token, DataTransferObjects.CardDTO card);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEditionContractChannel : TestConsoleClient.EditionService.IEditionContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EditionContractClient : System.ServiceModel.ClientBase<TestConsoleClient.EditionService.IEditionContract>, TestConsoleClient.EditionService.IEditionContract {
        
        public EditionContractClient() {
        }
        
        public EditionContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EditionContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EditionContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EditionContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool EditCard(DataTransferObjects.AuthenticationToken token, DataTransferObjects.CardDTO card) {
            return base.Channel.EditCard(token, card);
        }
        
        public System.Threading.Tasks.Task<bool> EditCardAsync(DataTransferObjects.AuthenticationToken token, DataTransferObjects.CardDTO card) {
            return base.Channel.EditCardAsync(token, card);
        }
    }
}
