//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsoleClient.RegistationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistationService.IRegistrationContract")]
    public interface IRegistrationContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationContract/RegisterUser", ReplyAction="http://tempuri.org/IRegistrationContract/RegisterUserResponse")]
        bool RegisterUser(DataTransferObjects.UserDTO user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationContract/RegisterUser", ReplyAction="http://tempuri.org/IRegistrationContract/RegisterUserResponse")]
        System.Threading.Tasks.Task<bool> RegisterUserAsync(DataTransferObjects.UserDTO user, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistrationContractChannel : TestConsoleClient.RegistationService.IRegistrationContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationContractClient : System.ServiceModel.ClientBase<TestConsoleClient.RegistationService.IRegistrationContract>, TestConsoleClient.RegistationService.IRegistrationContract {
        
        public RegistrationContractClient() {
        }
        
        public RegistrationContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrationContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegisterUser(DataTransferObjects.UserDTO user, string password) {
            return base.Channel.RegisterUser(user, password);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterUserAsync(DataTransferObjects.UserDTO user, string password) {
            return base.Channel.RegisterUserAsync(user, password);
        }
    }
}
